name: hadoop-spark-pig-hive

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  publish-hadoop-spark-pig-hive:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build the Docker image
        run: |
          docker build . --tag ghcr.io/joel/hadoop-spark-pig-hive:latest
          docker run ghcr.io/joel/hadoop-spark-pig-hive:latest
          docker push ghcr.io/joel/hadoop-spark-pig-hive:latest
      
      
